### ISSUE TITLE
flotCMS multilanguage?

### ISSUE THREAD

**Issue by FredMan95** [samthomson/flot#10]
I would like to translate flotCMS to Spanish. there is some possibility that it is multilanguage in the future?

**Comment by samthomson** [comment]
Hi, that sounds great, it's something I had planned. I'll schedule developing a feature to choose language, and re-architect the software to pull text from a language file. Then it will just be a case of translating one language file. I'll leave this issue open for now and post again when there's something to translate. Should be done within two weeks.
