### ISSUE TITLE
error when an element is deleted.

### ISSUE THREAD

**Issue by FredMan95** [samthomson/flot#11]
when an element is deleted this error occurs: 

404 Not Found

The requested URL /flot_flot/www/flot_flot/admin/'.S_BASE_EXTENSION.'flot_flot/admin/index.php was not found on this server.

**Comment by FredMan95** [comment]
This error also occurs when anything is deleted, as a webpage.

**Comment by FredMan95** [comment]
I fixed this. CLOSED. ;)

**Comment by samthomson** [comment]
I'll fix this tonight for the main branch.
