### ISSUE TITLE
Install shows blank page

### ISSUE THREAD

**Issue by intermedion** [samthomson/flot#12]
Installed flot in localhost subdirectory /flot; running http://localhost/flot/start.php gives a blank page and view source shows no page content.

Console error messages:

[Tue Oct 21 17:08:40 2014] [error] [client ::1] PHP Warning:  require(/Users/test/Sites/flot_flot/core/flot.php): failed to open stream: No such file or directory in /Users/test/Sites/flot/start.php on line 4

[Tue Oct 21 17:08:40 2014] [error] [client ::1] PHP Fatal error:  require(): Failed opening required '/Users/test/Sites/flot_flot/core/flot.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.2/lib/php') in /Users/test/Sites/flot/start.php on line 4

**Comment by Jugibur** [comment]
I have a blank page too, but without warnings (perhaps because of my PHP settings?)
Installed on OS X Mavericks, using MAMP with PHP 5.5.3

**Comment by Divian** [comment]
similar over here... Didn't manage to get it working.
os X Mavericks and MAMP with PHP Version 5.5.10

**Comment by samthomson** [comment]
Installing into a sub-directory was made possible some time ago, but to be honest I've been thinking of dropping it, I think it's a real edge case - and as such didn't bother to document how to set it up (you have to modify a file, adding the sub directory name) outside of the email stream with relevant user.

Flot is about to be majorly re-factored, as such I might think about re-implementing the sub-directory install feature.

**Comment by intermedion** [comment]
Could you perhaps post the modification needed to run the current version of Flot in a subdirectory?

Here are a few situations, not quite edge, where one might want to install Flot in a subdirectory:
- Developing and testing varions scripts in a localhost environment
- Using Flot in a hosted environment, along with other scripts

In both situations installing everything in the root might run into file/folder naming conflicts, besides creating a root full of dozens of files from various scripts

**Comment by samthomson** [comment]
Hi,

I can see your points, I was thinking more edge users than edge cases, as over all I think most people will just have one website per website folder, why not just make multiple websites?
Either way, I'll put subdirectory install back in - it could be usefu for enough people I suppose, and not much work to get it working nicely. However I'd rather everything in flot was 'native', without needing to hack config files to get it working. This being I'll do a little work Thursday evening to get it working from the start page with sub directory install.
Stay tuned, Sam.

**Comment by Divian** [comment]
Hi Sam,

Any progress on the situation? I'm still running on a blank page with the most recent version from github.

**Comment by samthomson** [comment]
Hmm, it was working during tests, I'm planning a massive re-factor of flot in the coming weeks, so stay tuned.

**Comment by ciptard** [comment]
Hi Sam,

I just came across this CMS, It's really awesome. I love the speed, and templating language which use nothing but HTML. But failed when I tried to install in a subdirectory.

Any updates for this issue? I hope there's a way for us to install it in a subdir without waiting the major refactor.

Thanks.

**Comment by samthomson** [comment]
Hi, Yeah it's a bit awkward though as you have to set a value in code in ~two config files with the subdirectory name. It will then break when updated to the latest version...
I have a couple of other projects keeping me busy just now, maybe return to flot afterwards.
