### ISSUE TITLE
Menu Generation

### ISSUE THREAD

**Issue by tyeeman** [samthomson/flot#15]
I managed to get my localhost with sub-domain working so I got flot installed just fine! Seems to work great except your menu generation starts with `<ul>`  then adds the list items. When I use my own templates and enter flot's tag for menu items, this  `<ul>` totally disables my templates styles for the menu. Why not just start with `<li>`, that would solve my problems with many of my templates.

**Comment by ciptard** [comment]
Hi,
would you mind sharing the tweaks you made to get it worked in subdirectory? I still can't figure it out. I had another CMS in my root folder, so the only way to try it is to install in a subdirectory.
Thanks.

**Comment by tyeeman** [comment]
Hi Sam 
I'm using apachefriends on Windows7 for my server. 

This describes how I did it - https://ardamis.com/2005/08/11/xampp-apache-namevirtualhost/ 

Here is the important content of my httpd-vhosts.conf file --- 

# 

# Use name-based virtual hosting.

# 

NameVirtualHost *:80 

# 

# VirtualHost example:

# Almost any Apache directive may go into a VirtualHost container.

# The first VirtualHost section is used for all requests that do not

# match a ##ServerName or ##ServerAlias in any <VirtualHost> block.

# 

<VirtualHost *:80> 
DocumentRoot "/xampp/htdocs" 
ServerName localhost 
</VirtualHost> 

<VirtualHost *:80> 
DocumentRoot "/xampp/htdocs/flot" 
ServerName flot.localhost 
</VirtualHost> 

Tony 

PS - I guess I can edit the code somewhere to remove the <ul> tags in the menu generation, yes? 

----- Original Message -----

**Comment by ciptard** [comment]
Thank you very much for the tips, I'll try it once I have the chance.

**Comment by tyeeman** [comment]
Ok, solved my problem in menu.php, lines 54 & 73, removed `<ul>` and `</ul>`

**Comment by samthomson** [comment]
"solved my problem" - I'll close the issue now then
