### ISSUE TITLE
Strange happenings when inserting links

### ISSUE THREAD

**Issue by tyeeman** [samthomson/flot#16]
Using the editor I insert a link and I get this - 

```
http://mydomain.net/membership/\"http://westcoastdave.ca/siska_dev/onlineregistration/smi_online_registration_new_renew.php\"
```

The link is supposed to start with the westcoastdave url, not to include the current page of my site. And yes I get the same thing when I insert the link in SOURCE code mode.

Update - saving the page a second time now deletes my link entirely and I only get a link of my current page.

```
http://mydomain.net/membership/\"\\\"

```

I much prefer Markdown editors. Is it possible to tell me how to change the wysiwyg editor to a markdown editor or have an option in the settings to enable the editor of choice?

I can't believe no one has found this yet. No one uses links I guess.

**Comment by samthomson** [comment]
Just pulled latest version and ran a test, couldn't reproduce your problem.
Can you give me some steps to reproduce.
I was able to create the link in two ways:
1. Using the insert link button in wysiwyg/gui
2. Switching to source view and manual entering a full a tag linking to your intended page.

Thanks for reporting!

**Comment by tyeeman** [comment]
Could it be because I'm using a sub-domain for flot? I will try to make a video of my process. 

Tony
