### ISSUE TITLE
Not Working On IIS

### ISSUE THREAD

**Issue by MattIPv4** [samthomson/flot#18]
I am trying to run this on IIS, but as mod_rewrite is not enabled, you cannot run the flot installer.
I have converted the .htaccess to web.config correctly, but the start.php will not run!

![image](https://cloud.githubusercontent.com/assets/12371363/8935805/8756f290-3546-11e5-8092-c8fece66740c.png)

**Comment by MattIPv4** [comment]
Fixed by removing Line 66 from flot-admin/core/utility.php

**Comment by MattIPv4** [comment]
Getting this error when i try to go the the "Settings" menu of the admin section.

[28-Jul-2015 16:45:19 Europe/Dublin] PHP Notice: Undefined property: stdClass::$max_width in C:[Removed - WebsiteBase]\flot-admin\core\admin_ui.php on line 270

**Comment by samthomson** [comment]
Hey,
Glad you got it working. mod_rewrite is a module which basically allows for catch all request handling. Not too experienced with IIS but it should exist as a php extension irrelevant of the platform so just a case of making sure it's enabled. Try looking in your phpinfo output.
Okay cool, that's a long standing 'bug' (it causes no problems). I'm just getting started on a re-work of flot, so it will soon be sorted.
