### ISSUE TITLE
Start.php Show A Blank Page

### ISSUE THREAD

**Issue by Xarcell** [samthomson/flot#19]
For some reason, when I try to install by visiting start.php, the page is blank.

**Comment by tyeeman** [comment]
I had the same problem. You must not be in the root directory so you must install there or use CPanel to create a subdomain like flot.yourdomain.com. That will work also.

I just tried another install locally using UWAMP, which I like better than apachefriends. It's real easy to make a virtual server to install flot locally. Let me know if you need assistance with that.

**Comment by samthomson** [comment]
Have you installed into a sub directory like tyeeman suggests out isn't supported?

**Comment by Xarcell** [comment]
Sorry for the reply, but today I placed FlotCMS in a subdomain and it worked.

**Comment by samthomson** [comment]
Great stuff!
