### ISSUE TITLE
Nearly solved my link problems

### ISSUE THREAD

**Issue by tyeeman** [samthomson/flot#20]
A long time ago I mentioned I had link problems when using the ckeditor. Extra quotes and slashes were being inserted into the links. You did not have that problem. I finally got around to searching and found out my server had php magic quotes turned on! They must be off for flot to create links correctly! So I searched again and found out I had to do this to turn them off in php 5.3 - 
1. add magic_quotes_gpc = off
   to the php.ini file
2. add suPHP_ConfigPath /home/yourid/public_html/
   to the .htaccess file.

This worked for me. With newer current php versions of 5.4 and greater those additions are NOT necessary because magic quotes are not supported anymore! Any way, I still have one problem left with links. I always get the main website url in front of any link I create in ckeditor. Now this is the weird part, if I look at the loaded web page source code I only see the link I created, such as google.com but when I move my cursor over that link, even in the source code, the actual link in the browser corner has my website url prepended to it like this - http://mydomain.com/google.com. So I still don't know if flot is doing this or ckeditor is. This happens on my live web server and also my local wamp server. Any tips?

Update - OK, I think I have solved it. Looks like I MUST use http:// to create urls in ckeditor. Then I don't get my site's url inserted in front of the url. Is this a flot or ckeditor limitation?

I still want to use markdown and will find out how to change the editor to some kind of markdown editor sooner or later. It would be nice to have a button to select between ckeditor or markdown.

How do I get more ckeditor options on the toolbar?

Creating links shows the full link on the page. Usually you highlight a word then create a link out of that. That method is not working here. Should it be?

**Comment by samthomson** [comment]
Flot is currently being re-wrote (v1 branch), so will take your findings into consideration. It should/will be possible to make internal relative links or external absolute links.

**Comment by tyeeman** [comment]
Thanks Sam! You've got a great cms here and I really like it. One thing I would like to run by you is if you can have an option to turn off minimization. If I'm troubleshooting something it's hard to see in the minimized code where to look, but then once everything is working good, turn on minimization again.

**Comment by samthomson** [comment]
For now it's not an option, but will add it to the next version. For now check out http://www.dirtymarkup.com/ you could copy paste the source of your page into it to help for now
