### ISSUE TITLE
Notice In FlotCMS Error Log

### ISSUE THREAD

**Issue by Xarcell** [samthomson/flot#21]
A Notice in the log on a fresh un-used/un-modified install: [02-Sep-2015 11:14:23 America/Chicago] PHP Notice: Undefined property: stdClass::$max_width in /home/xxxxxx/public_html/flotcms.xxxxxx.com/flot-admin/core/admin_ui.php on line 270

**Comment by samthomson** [comment]
Thanks, this is a known issue and will be fixed in the next major version release (branch v1).

**Comment by samthomson** [comment]
PS It doesn't effect the operation of flot.
