### ISSUE TITLE
impossible to insert images in ckeditor

### ISSUE THREAD

**Issue by jpacchioni** [samthomson/flot#7]
When I click the button "Insert Picture" once loaded does not allow me to enter it after you have clicked the "Insert Picture (s)".

**Comment by samthomson** [comment]
Thanks for reporting this, I'll fix it this evening.

**Comment by jpacchioni** [comment]
thank you for the fantastic job you're doing, not being a programmer I try
to help you by testing the cms

2014-06-11 10:35 GMT+02:00 samthomson notifications@github.com:

> Thanks for reporting this, I'll fix it this evening.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samthomson/flot/issues/7#issuecomment-45715515.

## 

http://www.jiabin.net/
Jacopo Pacchioni
web designer

phone.: +39 340 4901069
This e-mail and any file transmitted with may contain material that is
confidential, privileged and/or attorney work product for the sole use of
the intended recipient. If you are not intended recipient of this e-mail,
please do nor read this e-mail and notify us immediately and then delete
this message and any file attached from your system.

**Comment by jpacchioni** [comment]
thank you for the fantastic job you're doing, not being a programmer I try to help you by testing the cms

**Comment by samthomson** [comment]
Hi, no worries, thanks for reporting it and sorry it was there at all!
Flot's currently being re-factored a lot as new features are added - which allows some bugs in too, in a couple of features time I'll set up continuous integration and automated testing, so it will become more stable as it approaches version one.
Thanks again for reporting the bug and trying the beta.
