### ISSUE TITLE
Error on flot.php file

### ISSUE THREAD

**Issue by FredMan95** [samthomson/flot#9]
I installed flot for first time, all was well to configure the login details (email and password) and then log in, but when I logout and try log in again I get this error:

Notice: Use of undefined constant S_BASE_PATH - assumed 'S_BASE_PATH' in \flot_flot\core\flot.php on line 6

Warning: require_once(S_BASE_PATHflot_flot/core/base.php): failed to open stream: No such file or directory in \flot_flot\core\flot.php on line 6

Fatal error: require_once(): Failed opening required 'S_BASE_PATHflot_flot/core/base.php' (include_path='\php\pear') in \flot_flot\core\flot.php on line 6

**Comment by samthomson** [comment]
Thanks for reporting, will check out asap.

**Comment by samthomson** [comment]
Sorry for the delay, had a problem with my php dev environment, should be working now, let me know if you hit any problems
